export type ContentPageSlug = "home" | "about";

export type ContentPageContent = Record<string, string>;

export const contentPageDefaults: Record<ContentPageSlug, ContentPageContent> = {
  home: {
    heroEyebrow: "Real Teacher Insights",
    heroHeading: "DISCOVER THE REALITY OF WHAT TO EXPECT FROM A SCHOOL SITE BEFORE SAYING YES TO AN UNFAMILIAR GUEST-TEACHING OPPORTUNITY",
    primaryButtonLabel: "Submit a Report",
    primaryButtonHref: "/submit-report",
    secondaryButtonLabel: "Search School",
    secondaryButtonHref: "/browse-school",
    heroImage: "/homebanner.png",
    heroMockupImage: "/Artboard.svg",
    heroAnonymousLabel: "Anonymous Report",
    heroStatusLabel: "Enabled",
    heroReviewSchool: "Oakridge Academy",
    heroReviewSchoolType: "Public High School",
    heroReviewRating: "4.8 Rating",
    heroReviewTime: "2 days ago",
    whyHeading: "Why Guest-Teacher Report",
    whyStayAnonymousImage: "/anonymous.svg",
    whyStayAnonymousHeading: "Stay Anonymous",
    whyStayAnonymousDescription: "Share classroom experiences without revealing your identity.",
    whyStructuredReportsImage: "/reports.svg",
    whyStructuredReportsHeading: "Structured Reports",
    whyStructuredReportsDescription: "Access clear, experience-based insights from other educators.",
    whyBetterDecisionsImage: "/betterDecisions.svg",
    whyBetterDecisionsHeading: "Make Better Decisions",
    whyBetterDecisionsDescription: "Use real data to choose the right teaching assignments.",
    whySmartSearchImage: "/Frame.svg",
    whySmartSearchHeading: "Smart Search & Filters",
    whySmartSearchDescription: "Quickly find regular teacher or schools using powerful filters.",
    whyAiInsightsImage: "/ai.svg",
    whyAiInsightsHeading: "AI-Powered Insights",
    whyAiInsightsDescription: "Understand sentiment and patterns with intelligent analysis.",
    understandHeading: "Understand Every Classroom Before You Step In",
    understandDescription: "Explore detailed regular teacher profiles with aggregated reports, sentiment insights, and behavior patterns all in one structured view designed for clarity and confidence.",
    understandProfileLabel: "Profile",
    understandQuote: "Get the pulse of the building from those who work there every day.",
    understandRiskBadge: "Risk Level",
    understandPatternBadge: "Pattern-based insights",
    understandHistoryBadge: "Complete History",
    opportunitiesHeading: "Find the Right Opportunities with AI-Powered Insights",
    opportunitiesDescription: "Search regular teachers or schools, filter reports instantly, and uncover trends through intelligent sentiment analysis helping you make faster and more informed decisions.",
    opportunitiesImage: "/homeImage3.svg",
    opportunitiesSearchPlaceholder: "Search...",
    opportunitiesInsightsLabel: "Clear Insights",
    opportunitiesPositiveLabel: "Positive",
    opportunitiesNegativeLabel: "Negative",
    opportunitiesFilterLabel: "Filter results",
    stepsHeading: "How to Make Smarter Teaching Decisions in 3 Steps",
    stepsOneImage: "/one.svg",
    stepsOneHeading: "Submit Your Experience",
    stepsOneDescription: "Share detailed classroom insights with the option to remain anonymous.",
    stepsTwoImage: "/two.svg",
    stepsTwoHeading: "AI Analyzes & Structures",
    stepsTwoDescription: "Your report is reviewed, categorized with AI-powered sentiment insights to ensure clarity and consistency.",
    stepsThreeImage: "/three.svg",
    stepsThreeHeading: "Explore & Decide",
    stepsThreeDescription: "Search reports, review regular teacher profiles, and understand patterns before accepting assignments.",
    featureHeading: "Recent Reports Experiences",
    featureDescription: "Real insights shared by Guest teacher to help you better understand schools and teaching environments.",
    reportsLabel: "Reports",
    schoolsLabel: "Schools",
    verifiedUserLabel: "Verified User",
  },
  about: {
    heroEyebrow: "About Us",
    heroHeading: "Built for Guest Teachers,",
    heroHeadingAccent: "By Guest Teachers",
    heroDescription: "Guest Teacher Report exists to give substitute educators the knowledge, community, and confidence they deserve before they ever step through a classroom door.",
    primaryButtonLabel: "Browse Schools",
    primaryButtonHref: "/browse-school",
    secondaryButtonLabel: "Submit a Report",
    secondaryButtonHref: "/submit-report",
    howItWorksEyebrow: "How its Work",
    howItWorksHeading: "How Guest Teacher Report Works",
    howItWorksDescription: "A simple three-step loop that keeps the community informed, honest, and growing.",
    howItWorksOneHeading: "Submit a Report",
    howItWorksOneDescription: "After a school day, submit an anonymous review covering lesson plans, student behavior, staff support, and your overall experience. Takes under 3 minutes.",
    howItWorksTwoHeading: "Data Gets Analyzed",
    howItWorksTwoDescription: "Every report feeds our insight engine. We surface sentiment trends, recurring issues, and what's working well turning raw feedback into useful signals.",
    howItWorksThreeHeading: "Community Benefits",
    howItWorksThreeDescription: "Guest teachers browse real ratings before accepting assignments. Schools gain honest feedback to improve working conditions. Everyone wins.",
    problemEyebrow: "The Problem",
    problemHeading: "The Hesitant Substitute",
    problemContent: "Every guest teacher knows the feeling: the phone rings with a school assignment you've never heard of, and you have no way to know what to expect. Are the lesson plans ready? Will the staff support you? Are the students manageable?\n\nWithout information, you're forced to guess. Some accept assignments at shady schools repeatedly, burning out fast. Others turn down perfectly good placements out of an abundance of caution.\n\nGTR was created to resolve this uncertainty, giving you the peer-sourced intelligence to make confident choices about where you spend your professional time.",
    schoolsReviewedNumber: "2,400+",
    schoolsReviewedLabel: "Schools Reviewed",
    reportsSubmittedNumber: "18,000+",
    reportsSubmittedLabel: "Reports Submitted",
    guestTeachersNumber: "6,500+",
    guestTeachersLabel: "Guest Teachers",
    statesCoveredNumber: "34",
    statesCoveredLabel: "States Covered",
    whyEyebrow: "Our Why",
    whyHeading: "Why Guest Teacher Report?",
    whyDescription: "Because substitute teachers are the unsung backbone of the education system and they deserve the same transparency that any professional community expects.",
    whyAnonymousHeading: "Anonymous & Safe",
    whyAnonymousDescription: "No names, no retaliation, no school politics. You choose what to share and how much to identify yourself.",
    whyPeerSourcedHeading: "Peer-Sourced Truth",
    whyPeerSourcedDescription: "Ratings from real guest teachers who sat in that exact classroom — not marketing copy from a district office.",
    whyCommunityHeading: "Community Power",
    whyCommunityDescription: "The more teachers share, the more accurate and useful the platform becomes for everyone.",
    whyInsightsHeading: "Actionable Insights",
    whyInsightsDescription: "Not just stars — detailed breakdowns of lesson preparedness, behavior, admin support, and more.",
    guidelinesEyebrow: "Community Standards",
    guidelinesHeading: "Guest Teachers' Community Guidelines",
    guidelinesDescription: "GTR is only as trustworthy as its contributors. These guidelines keep our community fair, useful, and respectful.",
    guidelinesOneHeading: "Be honest, not hateful",
    guidelinesOneDescription: "Critique working conditions and professional circumstances. Do not target individual students, staff members, or protected characteristics.",
    guidelinesTwoHeading: "Write from personal experience",
    guidelinesTwoDescription: "Only submit reports for assignments you personally completed. Secondhand or fabricated reviews undermine the whole community.",
    guidelinesThreeHeading: "Be specific and constructive",
    guidelinesThreeDescription: "Vague ratings help no one. Mention what lesson materials were like, how behavior was managed, whether admin was accessible.",
    guidelinesFourHeading: "Respect anonymity — yours and others'",
    guidelinesFourDescription: "Don't include identifying information about specific students or staff. Protect the privacy of the classroom.",
    guidelinesFiveHeading: "One report per assignment",
    guidelinesFiveDescription: "Submitting multiple reviews of the same placement inflates data and distorts ratings for others in the community.",
    guidelinesSixHeading: "No promotional content",
    guidelinesSixDescription: "GTR is not a place for staffing agency ads, tutoring promos, or unrelated solicitation of any kind.",
    overviewEyebrow: "Who We Are",
    overviewQuote: "We believe substitute teachers are professionals who deserve professional-grade information about their workplace.",
    overviewAttribution: "GTR Founding Team",
    overviewHeading: "About Guest Teacher Report",
    overviewContent: "Guest Teacher Report is an independent platform founded by former substitute teachers and educators who experienced firsthand the challenges of walking into an unfamiliar school. We're not affiliated with any school district, staffing agency, or government body.\n\nOur team spans educators, technologists, and community builders who are committed to a simple belief: better information creates better outcomes — for teachers, for students, and for schools.\n\nEvery feature we build and every improvement we make is guided by one goal: to remain a free, trusted resource for all guest teachers across the United States and beyond.",
    schoolsEyebrow: "For Schools",
    schoolsHeading: "How Schools & Districts Benefit",
    schoolsDescription: "GTR isn't just for guest teachers. Forward-thinking schools use the platform to attract better subs and continuously improve.",
    schoolsOneHeading: "Attract Quality Subs",
    schoolsOneDescription: "Schools with high ratings become first-choice destinations. Great reviews mean guest teachers actively seek out your assignments.",
    schoolsTwoHeading: "Honest Feedback Loop",
    schoolsTwoDescription: "Aggregate reports surface systemic issues — from missing lesson plans to administration gaps that formal channels often miss.",
    schoolsThreeHeading: "Improve Retention",
    schoolsThreeDescription: "When guest teachers feel supported, schools experience lower hiring costs and maintain a consistent, stable classroom environment.",
    directionEyebrow: "Our Direction",
    directionHeading: "Mission, Vision & Goal Statement",
    missionLabel: "Mission",
    missionDescription: "To empower substitute teachers with transparent, peer-sourced school insights that support informed, confident, and dignified professional decisions.",
    visionLabel: "Vision",
    visionDescription: "A world where every guest teacher walks into every classroom fully prepared — and every school competes to be a place subs genuinely want to work.",
    goalLabel: "Goal",
    goalDescription: "To become the most trusted, comprehensive, and widely-used school review platform for substitute teachers across the United States and beyond.",
  },
};

export const contentPageMetadata: Record<ContentPageSlug, { title: string; path: string; description: string }> = {
  home: {
    title: "Home",
    path: "/",
    description: "Landing page hero, calls to action, featured content.",
  },
  about: {
    title: "About Us",
    path: "/about",
    description: "About page hero, calls to action, and long-form organization content.",
  },
};

export function isContentPageSlug(value: unknown): value is ContentPageSlug {
  return value === "home" || value === "about";
}

export function mergeContentPage(slug: ContentPageSlug, content: unknown): ContentPageContent {
  const defaults = contentPageDefaults[slug];

  if (!content || typeof content !== "object" || Array.isArray(content)) {
    return defaults;
  }

  return Object.fromEntries(
    Object.entries(defaults).map(([key, fallback]) => [
      key,
      typeof (content as Record<string, unknown>)[key] === "string"
        ? (content as Record<string, string>)[key]
        : fallback,
    ])
  );
}
