create table if not exists public.contact_inquiries (
  id bigint generated by default as identity primary key,
  full_name text not null,
  email text not null,
  subject text not null,
  message text not null,
  status text not null default 'new' check (status in ('new', 'read', 'resolved')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists contact_inquiries_status_idx on public.contact_inquiries(status);
create index if not exists contact_inquiries_created_at_idx on public.contact_inquiries(created_at desc);

alter table public.contact_inquiries enable row level security;
