create table if not exists public.school_access_requests (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  user_id bigint not null references public.users(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected', 'revoked')),
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  decided_by bigint references public.users(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (school_id, user_id)
);

create index if not exists school_access_requests_user_idx on public.school_access_requests(user_id);
create index if not exists school_access_requests_school_idx on public.school_access_requests(school_id);
create index if not exists school_access_requests_status_idx on public.school_access_requests(status);

alter table public.school_access_requests enable row level security;
